/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.71.1
  Forc version: 0.48.1
  Fuel-Core version: 0.22.0
*/

export type { PainterContractAbi } from './PainterContractAbi';

export { PainterContractAbi__factory } from './factories/PainterContractAbi__factory';
